using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace uib3pn_IRF_project.Entities
{
    public enum CountryEnum
    {
        Algeria = 1,
        AmericanSamoa = 2,
        Anguilla = 3,
        Antarctica = 4,
        Armenia = 5,
        Austria = 6,
        Bahrain = 7,
        Bangladesh = 8,
        Belgium = 9,
        Belize = 10,
        Bhutan = 11,
        Bulgaria = 12,
        Burundi = 13,
        CaymanIslands = 14,
        CentralAfricanRepublic = 15,
        Chad = 16,
        ChristmasIsland = 17,
        Comoros = 18,
        CongotheDemocraticRepublicofthe = 19,
        Croatia = 20,
        DominicanRepublic = 21,
        Egypt = 22,
        FalklandIslands = 23,
        Gambia = 24,
        Georgia = 25,
        Germany = 26,
        Gibraltar = 27,
        Greenland = 28,
        Guadeloupe = 29,
        Guatemala = 30,
        Guernsey = 31,
        Haiti = 32,
        HeardIslandandMcdonaldIslands = 33,
        HolySeeVaticanCityState=34,
        Honduras = 35,
        IsleofMan = 36,
        Israel = 37,
        Jordan = 38,
        Kazakhstan = 39,
        KoreaSouth = 40,
        Kyrgyzstan = 41,
        Laos = 42,
        Latvia = 43,
        Liberia = 44,
        Lithuania = 45,
        Martinique = 46,
        Mauritania = 47,
        Mayotte = 48,
        Mexico = 49,
        Montenegro = 50,
        Morocco = 51,
        Myanmar = 52,
        Namibia = 53,
        Nepal = 54,
        Netherlands = 55,
        Nigeria = 56,
        NorfolkIsland = 57,
        PalestineStateof = 58,
        Poland = 59,
        Qatar = 60,
        RussianFederation = 61,
        SaintHelenaAscensionandTristandaCunha = 62,
        Senegal = 63,
        Serbia = 64,
        SintMaarten = 65,
        Slovakia = 66,
        Somalia = 67,
        Sudan = 68,
        Suriname = 69,
        Swaziland = 70,
        Sweden = 71,
        Switzerland = 72,
        Syria = 73,
        Tajikistan = 74,
        Tonga = 75,
        Tunisia = 76,
        UnitedStatesMinorOutlyingIslands = 77,
        Vanuatu = 78,
        WallisandFutuna = 79,
        WesternSahara = 80,
        Yemen = 81,
        Zimbabwe = 82
    }
}
